apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: irhadudheen/auth-levelup:latest
        ports:
        - containerPort: 4000
       
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: backend
spec:
  selector:
    app: auth-service
  ports:
  - port: 4000
    targetPort: 4000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: subject-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subject-service
  template:
    metadata:
      labels:
        app: subject-service
    spec:
      containers:
      - name: subject-service
        image: irhadudheen/subject-levelup:latest
        ports:
        - containerPort: 4002
        
---
apiVersion: v1
kind: Service
metadata:
  name: subject-service
  namespace: backend
spec:
  selector:
    app: subject-service
  ports:
  - port: 4002
    targetPort: 4002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: irhadudheen/payment-levelup:latest
        ports:
        - containerPort: 3001
       
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  namespace: backend
spec:
  selector:
    app: payment-service
  ports:
  - port: 3001
    targetPort: 3001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interview-service
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interview-service
  template:
    metadata:
      labels:
        app: interview-service
    spec:
      containers:
      - name: interview-service
        image: irhadudheen/interview-levelup:latest
        ports:
        - containerPort: 4005
       
---
apiVersion: v1
kind: Service
metadata:
  name: interview-service
  namespace: backend
spec:
  selector:
    app: interview-service
  ports:
  - port: 4005
    targetPort: 4005

