apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq-deployment
  namespace: backend  # Added namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3.12.14-management
          ports:
            - containerPort: 5672
            - containerPort: 15672
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "admin"
            - name: RABBITMQ_DEFAULT_PASS
              value: "admin123"
          resources:
            limits:
              cpu: "500m" # Example CPU limit
              memory: "512Mi" # Example memory limit
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: backend  # Added namespace
  labels:
    app: rabbitmq
spec:
  selector:
    app: rabbitmq
  ports:
   - port: 5672
     name: amqp
   - port: 15672
     name: management
  type: ClusterIP
