apiVersion: v1
kind: Namespace
metadata:
  name: compiler-namespace  # Replace with your actual namespace name

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: compiler-namespace  # Use your actual namespace
  name: pod-exec-role
rules:
- apiGroups: [""]
  resources: ["pods", "pods/exec"]
  verbs: ["get", "list", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-rolebinding
  namespace: compiler-namespace  # Use your actual namespace
subjects:
- kind: ServiceAccount
  name: default  # Or the name of your specific ServiceAccount
  namespace: compiler-namespace  # Use your actual namespace
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io