---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: compiler
  name: configmap-creator
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: configmap-creator-binding
  namespace: compiler
subjects:
- kind: ServiceAccount
  name: default
  namespace: compiler
roleRef:
  kind: Role
  name: configmap-creator
  apiGroup: rbac.authorization.k8s.io