name: Docker Login

on:
  push:
    branches:
      - master 

jobs:
  docker-login:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: -u irhadudheen
          password: ${{secrets.DOCKER_PASSWORD}}
